// swift-tools-version: 5.9

import PackageDescription

/// RemoteDraw's Swift sender SDK.
///
/// Two targets, split the way `docs/plans/ios-sender-sdk.md` §9.1 asks for:
///
/// - `RemoteDrawInk` — the tapered dynamic ribbons, shared with the web
///   (`packages/client/src/inkGeometry.ts`) and with the first-party app.
///   `RemoteDrawInk` is the sole source of truth for the renderer — the app
///   compiles this target's source directly — so a stroke drawn through the
///   SDK is the same mark as a stroke drawn in the app.
/// - `RemoteDrawSenderKit` — the headless sender: capture, codec, budgets,
///   transport, session lifecycle. Re-exports `RemoteDrawInk`, so a customer
///   writes one `import`.
///
/// Deliberately one *package* with two targets rather than two packages: §8.3
/// exports `apps/ios/RemoteDrawSenderKit/**` into the public mirror and runs
/// `swift test` there to prove the export is self-contained, which a
/// cross-package dependency would break.
///
/// No external dependencies, on purpose. A customer's dependency graph gains
/// exactly one node.
let package = Package(
  name: "RemoteDrawSenderKit",
  platforms: [
    .iOS(.v17),
    .macOS(.v14),
  ],
  products: [
    .library(name: "RemoteDrawSenderKit", targets: ["RemoteDrawSenderKit"]),
    .library(name: "RemoteDrawInk", targets: ["RemoteDrawInk"]),
  ],
  targets: [
    .target(name: "RemoteDrawInk"),
    .target(
      name: "RemoteDrawSenderKit",
      dependencies: ["RemoteDrawInk"],
      resources: [
        // Apple merges a source target's manifest into the host app's privacy
        // report at archive time. It covers `RemoteDrawInk` too — the two ship
        // as one package and a customer cannot take the renderer without the
        // sender.
        .copy("Resources/PrivacyInfo.xcprivacy")
      ]
    ),
    // The renderer's own tests. A separate bundle because they reach
    // `InkRenderer` internals — the surface table, the profile constants, the
    // frame-cost measurements — and `@testable import` only reaches into the
    // target it names. They ran in the first-party app until Stage 2, where the
    // app stopped compiling the renderer's source and lost the access.
    .testTarget(
      name: "RemoteDrawInkTests",
      // `RemoteDrawSenderKit` too, and only for one test: `SurfaceRenderParityTests`
      // renders the pre-Stage-2 draw pass and the new `RemoteDrawBoardCanvas`
      // into the same bitmap and compares them. It needs the old code's
      // internals (this target) and the new view (that one) in one process.
      dependencies: ["RemoteDrawInk", "RemoteDrawSenderKit"]
    ),
    .testTarget(
      name: "RemoteDrawSenderKitTests",
      dependencies: ["RemoteDrawSenderKit"],
      resources: [
        // Generated by `bun run scripts/point-codec-fixtures.ts`. Never edited
        // by hand — that is the whole point of it existing.
        .copy("Fixtures/pointCodecVectors.json"),
        // A verbatim copy of `packages/geometry/tests/fixtures/mapBoardGeometryVectors.json`,
        // which the TypeScript half of the same math checks itself against.
        // Copied rather than referenced because §8.3 exports this package alone
        // into the public mirror and runs `swift test` there: a path out of the
        // package would make that export a lie. Re-copy it when the shared table
        // changes; `MapGeometryTests` fails loudly if the two drift.
        .copy("Fixtures/mapBoardGeometryVectors.json")
      ]
    ),
  ]
)
